// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeMkv(arg1) {
  return window['go']['main']['App']['AnalyzeMkv'](arg1);
}

export function BuildFilename(arg1) {
  return window['go']['main']['App']['BuildFilename'](arg1);
}

export function CancelMux() {
  return window['go']['main']['App']['CancelMux']();
}

export function FileSize(arg1) {
  return window['go']['main']['App']['FileSize'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLihdlOptions() {
  return window['go']['main']['App']['GetLihdlOptions']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function LocateMkvmerge() {
  return window['go']['main']['App']['LocateMkvmerge']();
}

export function Mux(arg1) {
  return window['go']['main']['App']['Mux'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SearchTmdb(arg1) {
  return window['go']['main']['App']['SearchTmdb'](arg1);
}

export function SelectMkvFile() {
  return window['go']['main']['App']['SelectMkvFile']();
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}

export function SelectSubFiles() {
  return window['go']['main']['App']['SelectSubFiles']();
}

export function TestTmdbKey(arg1) {
  return window['go']['main']['App']['TestTmdbKey'](arg1);
}

export function VideoTrackName(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['VideoTrackName'](arg1, arg2, arg3, arg4);
}
