// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {naming} from '../models';
import {config} from '../models';
import {main} from '../models';
import {tmdb} from '../models';

export function AnalyzeMkv(arg1:string):Promise<void>;

export function BuildFilename(arg1:naming.FilenameParams):Promise<string>;

export function CancelMux():Promise<void>;

export function FileSize(arg1:string):Promise<number>;

export function GetConfig():Promise<config.Config>;

export function GetLihdlOptions():Promise<main.LihdlOptions>;

export function GetVersion():Promise<string>;

export function LocateMkvmerge():Promise<string>;

export function Mux(arg1:main.MuxRequest):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SearchTmdb(arg1:string):Promise<Array<tmdb.Result>>;

export function SelectMkvFile():Promise<string>;

export function SelectOutputDir():Promise<string>;

export function SelectSubFiles():Promise<Array<string>>;

export function TestTmdbKey(arg1:string):Promise<main.TmdbTestResult>;

export function VideoTrackName(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;
