// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {naming} from '../models';
import {main} from '../models';
import {audiosync} from '../models';
import {config} from '../models';
import {tmdb} from '../models';

export function AnalyzeMkv(arg1:string):Promise<void>;

export function AnalyzeMkvSecondary(arg1:string):Promise<void>;

export function BuildFilename(arg1:naming.FilenameParams):Promise<string>;

export function CancelMux():Promise<void>;

export function CheckUpdate():Promise<main.UpdateInfo>;

export function CheckVFQ(arg1:string):Promise<boolean>;

export function DetectAudioOffset(arg1:string,arg2:number,arg3:number):Promise<audiosync.DetectionResult>;

export function ExtractRefSubs(arg1:string):Promise<Array<main.RefSubResult>>;

export function FileSize(arg1:string):Promise<number>;

export function GetConfig():Promise<config.Config>;

export function GetLihdlOptions():Promise<main.LihdlOptions>;

export function GetMkvBasicInfo(arg1:string):Promise<main.MkvBasicInfo>;

export function GetVersion():Promise<string>;

export function InstallUpdate():Promise<void>;

export function ListAudioTracksForSync(arg1:string):Promise<Array<main.SyncAudioTrack>>;

export function LocateMkvmerge():Promise<string>;

export function LookupHydrackerURL(arg1:number):Promise<string>;

export function MoveToTrash(arg1:Array<string>):Promise<void>;

export function Mux(arg1:main.MuxRequest):Promise<void>;

export function MuxAudioSync(arg1:main.AudioSyncRequest):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SearchTmdb(arg1:string):Promise<Array<tmdb.Result>>;

export function SearchTmdbMovie(arg1:string):Promise<Array<tmdb.Result>>;

export function SearchTmdbTV(arg1:string):Promise<Array<tmdb.Result>>;

export function SelectAudioFiles():Promise<Array<string>>;

export function SelectMkvFile():Promise<string>;

export function SelectOutputDir():Promise<string>;

export function SelectSubFiles():Promise<Array<string>>;

export function TestHydrackerKey(arg1:string):Promise<main.ApiKeyTestResult>;

export function TestTmdbKey(arg1:string):Promise<main.TmdbTestResult>;

export function TestUnfrKey(arg1:string):Promise<main.ApiKeyTestResult>;

export function VideoTrackName(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;
