// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeMkv(arg1) {
  return window['go']['main']['App']['AnalyzeMkv'](arg1);
}

export function AnalyzeMkvSecondary(arg1) {
  return window['go']['main']['App']['AnalyzeMkvSecondary'](arg1);
}

export function ApplyOCRFix(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ApplyOCRFix'](arg1, arg2, arg3, arg4);
}

export function BuildFilename(arg1) {
  return window['go']['main']['App']['BuildFilename'](arg1);
}

export function CancelMux() {
  return window['go']['main']['App']['CancelMux']();
}

export function CheckSubsSync(arg1, arg2) {
  return window['go']['main']['App']['CheckSubsSync'](arg1, arg2);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CheckVFQ(arg1) {
  return window['go']['main']['App']['CheckVFQ'](arg1);
}

export function DetectAudioOffset(arg1, arg2, arg3) {
  return window['go']['main']['App']['DetectAudioOffset'](arg1, arg2, arg3);
}

export function DiscordIndexLookup(arg1) {
  return window['go']['main']['App']['DiscordIndexLookup'](arg1);
}

export function DiscordIndexPushGitHub() {
  return window['go']['main']['App']['DiscordIndexPushGitHub']();
}

export function DiscordIndexRead() {
  return window['go']['main']['App']['DiscordIndexRead']();
}

export function DiscordIndexRefreshRemote() {
  return window['go']['main']['App']['DiscordIndexRefreshRemote']();
}

export function DiscordIndexScan() {
  return window['go']['main']['App']['DiscordIndexScan']();
}

export function DownloadOpenSubtitle(arg1, arg2) {
  return window['go']['main']['App']['DownloadOpenSubtitle'](arg1, arg2);
}

export function ExtractFRAudios(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExtractFRAudios'](arg1, arg2, arg3, arg4, arg5);
}

export function ExtractRefSubs(arg1, arg2) {
  return window['go']['main']['App']['ExtractRefSubs'](arg1, arg2);
}

export function FileSize(arg1) {
  return window['go']['main']['App']['FileSize'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLihdlOptions() {
  return window['go']['main']['App']['GetLihdlOptions']();
}

export function GetMkvBasicInfo(arg1) {
  return window['go']['main']['App']['GetMkvBasicInfo'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function ListAudioTracksForSync(arg1) {
  return window['go']['main']['App']['ListAudioTracksForSync'](arg1);
}

export function LocateMkvmerge() {
  return window['go']['main']['App']['LocateMkvmerge']();
}

export function LookupHydrackerURL(arg1) {
  return window['go']['main']['App']['LookupHydrackerURL'](arg1);
}

export function MoveDirContentsToTrash(arg1) {
  return window['go']['main']['App']['MoveDirContentsToTrash'](arg1);
}

export function MoveToTrash(arg1) {
  return window['go']['main']['App']['MoveToTrash'](arg1);
}

export function Mux(arg1) {
  return window['go']['main']['App']['Mux'](arg1);
}

export function MuxAudioSync(arg1) {
  return window['go']['main']['App']['MuxAudioSync'](arg1);
}

export function OCRCustomDictAdd(arg1, arg2, arg3) {
  return window['go']['main']['App']['OCRCustomDictAdd'](arg1, arg2, arg3);
}

export function OCRCustomDictList() {
  return window['go']['main']['App']['OCRCustomDictList']();
}

export function OCRCustomDictRemove(arg1) {
  return window['go']['main']['App']['OCRCustomDictRemove'](arg1);
}

export function OCRPGSTrack(arg1, arg2, arg3) {
  return window['go']['main']['App']['OCRPGSTrack'](arg1, arg2, arg3);
}

export function OCRSupFile(arg1, arg2) {
  return window['go']['main']['App']['OCRSupFile'](arg1, arg2);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SearchOpenSubtitles(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchOpenSubtitles'](arg1, arg2, arg3);
}

export function SearchTmdb(arg1) {
  return window['go']['main']['App']['SearchTmdb'](arg1);
}

export function SearchTmdbMovie(arg1) {
  return window['go']['main']['App']['SearchTmdbMovie'](arg1);
}

export function SearchTmdbTV(arg1) {
  return window['go']['main']['App']['SearchTmdbTV'](arg1);
}

export function SelectAudioFiles() {
  return window['go']['main']['App']['SelectAudioFiles']();
}

export function SelectMkvFile() {
  return window['go']['main']['App']['SelectMkvFile']();
}

export function SelectMkvFiles() {
  return window['go']['main']['App']['SelectMkvFiles']();
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}

export function SelectSubFiles() {
  return window['go']['main']['App']['SelectSubFiles']();
}

export function SelectSupFiles() {
  return window['go']['main']['App']['SelectSupFiles']();
}

export function TestHydrackerKey(arg1) {
  return window['go']['main']['App']['TestHydrackerKey'](arg1);
}

export function TestLanguageToolKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestLanguageToolKey'](arg1, arg2, arg3);
}

export function TestTmdbKey(arg1) {
  return window['go']['main']['App']['TestTmdbKey'](arg1);
}

export function TestUnfrKey(arg1) {
  return window['go']['main']['App']['TestUnfrKey'](arg1);
}

export function VideoTrackName(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['VideoTrackName'](arg1, arg2, arg3, arg4);
}
