// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeMkv(arg1) {
  return window['go']['main']['App']['AnalyzeMkv'](arg1);
}

export function AnalyzeMkvSecondary(arg1) {
  return window['go']['main']['App']['AnalyzeMkvSecondary'](arg1);
}

export function BuildFilename(arg1) {
  return window['go']['main']['App']['BuildFilename'](arg1);
}

export function CancelMux() {
  return window['go']['main']['App']['CancelMux']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CheckVFQ(arg1) {
  return window['go']['main']['App']['CheckVFQ'](arg1);
}

export function FileSize(arg1) {
  return window['go']['main']['App']['FileSize'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLihdlOptions() {
  return window['go']['main']['App']['GetLihdlOptions']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function LocateMkvmerge() {
  return window['go']['main']['App']['LocateMkvmerge']();
}

export function LookupHydrackerURL(arg1) {
  return window['go']['main']['App']['LookupHydrackerURL'](arg1);
}

export function MoveToTrash(arg1) {
  return window['go']['main']['App']['MoveToTrash'](arg1);
}

export function Mux(arg1) {
  return window['go']['main']['App']['Mux'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SearchTmdb(arg1) {
  return window['go']['main']['App']['SearchTmdb'](arg1);
}

export function SearchTmdbMovie(arg1) {
  return window['go']['main']['App']['SearchTmdbMovie'](arg1);
}

export function SearchTmdbTV(arg1) {
  return window['go']['main']['App']['SearchTmdbTV'](arg1);
}

export function SelectAudioFiles() {
  return window['go']['main']['App']['SelectAudioFiles']();
}

export function SelectMkvFile() {
  return window['go']['main']['App']['SelectMkvFile']();
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}

export function SelectSubFiles() {
  return window['go']['main']['App']['SelectSubFiles']();
}

export function TestHydrackerKey(arg1) {
  return window['go']['main']['App']['TestHydrackerKey'](arg1);
}

export function TestTmdbKey(arg1) {
  return window['go']['main']['App']['TestTmdbKey'](arg1);
}

export function TestUnfrKey(arg1) {
  return window['go']['main']['App']['TestUnfrKey'](arg1);
}

export function VideoTrackName(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['VideoTrackName'](arg1, arg2, arg3, arg4);
}
